// Builds the marketing pages into /public from /site. Run: npm run build
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pages } from '../site/pages.js';
import { layout } from '../site/layout.js';
import { SITE_URL } from '../site/site.config.js';
import { ICONS } from '../src/lib/icons.js';
import { RESERVED, HANDLE_RE } from '../src/lib/handles.js';
import { expand } from '../site/cards.js';
import { THEMES } from '../src/lib/themes.js';
import { categories, themeCopy, cats } from '../site/catalogue.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = p => join(root, 'public', p);
// Writes only when the content changed, so `wrangler dev` (which watches src/ and re-runs this
// build) doesn't loop on its own output.
const writeIfChanged = async (file, c) => {
  const old = await readFile(file, 'utf8').catch(() => null);
  if (old === c) return;
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, c);
};
const write = (p, c) => writeIfChanged(out(p), c);

for (const p of pages) {
  const body = (await readFile(join(root, 'site/pages', p.name + '.html'), 'utf8'));
  await write(p.out, layout(p, expand(body)));
}

await write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...pages.filter(p => p.sitemap).map(p => p.path), '/create'].map(u => `  <url><loc>${SITE_URL}${u}</loc></url>`).join('\n')}
</urlset>
`);

// Browser copy of the shared icon set (single source: src/lib/icons.js)
await write('assets/js/icons.js', '// Generated by scripts/build.mjs from src/lib/icons.js. Do not edit.\nwindow.LC_ICONS = ' + JSON.stringify(ICONS) + ';\n');

// Browser copy of the handle rules (single source: src/lib/handles.js)
await write('assets/js/rules.js', '// Generated by scripts/build.mjs from src/lib/handles.js. Do not edit.\nwindow.LC_RULES = ' + JSON.stringify({ reserved: [...RESERVED].sort(), pattern: HANDLE_RE.source }) + ';\n');

// Browser design catalogue: marketing copy (site/catalogue.js) + colours (single source: src/lib/themes.js).
// themes: key → [name, category, bg, ink, button, button ink, sample person, sample role] (read by site.js).
const themes = Object.fromEntries(Object.entries(themeCopy).map(([k, [name, cat, person, role]]) => {
  const t = THEMES[k];
  if (!t) throw new Error(`site/catalogue.js: colourway "${k}" is not in src/lib/themes.js`);
  return [k, [name, cat, t.bg, t.ink, t.btn, t.btnInk, person, role]];
}));
await write('assets/js/catalogue.js', '// Generated by scripts/build.mjs from site/catalogue.js and src/lib/themes.js. Do not edit.\nwindow.LC = ' + JSON.stringify({ categories, themes, cats }) + ';\n');

console.log(`Built ${pages.length} pages.`);
