// Builds the marketing pages into /public from /site. Run: npm run build
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pages } from '../site/pages.js';
import { layout } from '../site/layout.js';
import { SITE_URL } from '../site/site.config.js';
import { ICONS } from '../src/lib/icons.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = p => join(root, 'public', p);
const write = async (p, c) => { await mkdir(dirname(out(p)), { recursive: true }); await writeFile(out(p), c); };

for (const p of pages) {
  const body = await readFile(join(root, 'site/pages', p.name + '.html'), 'utf8');
  await write(p.out, layout(p, body));
}

await write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...pages.filter(p => p.sitemap).map(p => p.path), '/create'].map(u => `  <url><loc>${SITE_URL}${u}</loc></url>`).join('\n')}
</urlset>
`);

// Browser copy of the shared icon set (single source: src/lib/icons.js)
await write('assets/js/icons.js', '// Generated by scripts/build.mjs from src/lib/icons.js. Do not edit.\nwindow.LC_ICONS = ' + JSON.stringify(ICONS) + ';\n');

console.log(`Built ${pages.length} pages.`);
