// Builds the marketing pages into /public from /site. Run: npm run build
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pages } from '../site/pages.js';
import { layout } from '../site/layout.js';
import { SITE_URL, TURNSTILE_SITE_KEY } from '../site/site.config.js';
import { ICONS } from '../src/lib/icons.js';
import { RESERVED } from '../src/lib/handles.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = p => join(root, 'public', p);
// Writes only when the content changed, so `wrangler dev` (which watches src/ and re-runs this
// build) doesn't loop on its own output.
const writeIfChanged = async (file, c) => {
  const old = await readFile(file, 'utf8').catch(() => null);
  if (old === c) return;
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, c);
};
const write = (p, c) => writeIfChanged(out(p), c);

for (const p of pages) {
  const body = (await readFile(join(root, 'site/pages', p.name + '.html'), 'utf8')).replaceAll('{{TURNSTILE_SITE_KEY}}', TURNSTILE_SITE_KEY);
  await write(p.out, layout(p, body));
}

await write('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...pages.filter(p => p.sitemap).map(p => p.path), '/create'].map(u => `  <url><loc>${SITE_URL}${u}</loc></url>`).join('\n')}
</urlset>
`);

// Browser copy of the shared icon set (single source: src/lib/icons.js)
await write('assets/js/icons.js', '// Generated by scripts/build.mjs from src/lib/icons.js. Do not edit.\nwindow.LC_ICONS = ' + JSON.stringify(ICONS) + ';\n');

// Browser copy of the handle rules (single source: src/lib/handles.js)
await write('assets/js/rules.js', '// Generated by scripts/build.mjs from src/lib/handles.js. Do not edit.\nwindow.LC_RULES = ' + JSON.stringify({ reserved: [...RESERVED].sort() }) + ';\n');

// Worker copy of the QR generator (single source: public/app/qrcode.js, vendored from NexBizRise)
const qr = await readFile(join(root, 'public/app/qrcode.js'), 'utf8');
if (!/window\.qrcode = qrcode;\s*$/.test(qr)) throw new Error('public/app/qrcode.js changed shape; update scripts/build.mjs');
await writeIfChanged(join(root, 'src/lib/qrcode.gen.js'), '// Generated by scripts/build.mjs from public/app/qrcode.js. Do not edit.\n' + qr.replace(/window\.qrcode = qrcode;\s*$/, 'export default qrcode;\n'));

console.log(`Built ${pages.length} pages.`);
